#Listado de indices
NEIGHBORHOOD_UP = 0
NEIGHBORHOOD_DOWN = 1
NEIGHBORHOOD_RIGHT = 2
NEIGHBORHOOD_LEFT = 3
NEIGHBORHOOD_DIST_UP = 4
NEIGHBORHOOD_DIST_DOWN = 5
NEIGHBORHOOD_DIST_RIGHT = 6
NEIGHBORHOOD_DIST_LEFT = 7
PLAYER_X = 8
PLAYER_Y = 9
COMMAND_CENTER_X = 10
COMMAND_CENTER_Y = 11
AGENT_X = 12
AGENT_Y = 13
CAN_FIRE = 14
HEALTH = 15

#Items en el mapa
NOTHING = 0
UNBREAKABLE = 1
BRICK = 2
COMMAND_CENTER = 3
PLAYER = 4
SHELL = 5
OTHER = 6

#Movimientos posibles
STAY = 0
MOVE_UP = 1
MOVE_DOWN = 2
MOVE_RIGHT = 3
MOVE_LEFT = 4

#Movimiento del NPC
#Creamos los siguientes arrays de informacion para evitar la repeticion de codigo con tantos ifs
movingDirs = [MOVE_UP, MOVE_DOWN, MOVE_RIGHT, MOVE_LEFT]
dirs = [NEIGHBORHOOD_UP, NEIGHBORHOOD_DOWN, NEIGHBORHOOD_RIGHT, NEIGHBORHOOD_LEFT]
dist = [NEIGHBORHOOD_DIST_UP, NEIGHBORHOOD_DIST_DOWN, NEIGHBORHOOD_DIST_RIGHT, NEIGHBORHOOD_DIST_LEFT]

#Estados del NPC
EXPLORE = 0
DEFEND = 1
ATTACK = 2

